# Generated by Django 4.2.13 on 2024-06-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
